language: groovy

deploy:
  provider: script
  script: echo -e "gradle.publish.key=$APIKEY\ngradle.publish.secret=$APISECRET" > gradle.properties && gradle publishPlugins
  skip_cleanup: true
  on:
    tags: true